//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeIPAdress.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChangeIPWin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangeIPWin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChangeIPAdress.Resources.ChangeIPWin", typeof(ChangeIPWin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change IP Address.
        /// </summary>
        internal static string FrmMainTxt {
            get {
                return ResourceManager.GetString("FrmMainTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string grpDetailsTxt {
            get {
                return ResourceManager.GetString("grpDetailsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile.
        /// </summary>
        internal static string grpProfilesTxt {
            get {
                return ResourceManager.GetString("grpProfilesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically....
        /// </summary>
        internal static string lblAutomaticallyTxt {
            get {
                return ResourceManager.GetString("lblAutomaticallyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error..
        /// </summary>
        internal static string lblErrorDBTxt {
            get {
                return ResourceManager.GetString("lblErrorDBTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway.
        /// </summary>
        internal static string lblGatewayTxt {
            get {
                return ResourceManager.GetString("lblGatewayTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string lblIPAddressTxt {
            get {
                return ResourceManager.GetString("lblIPAddressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Subnet.
        /// </summary>
        internal static string lblIPSubnetTxt {
            get {
                return ResourceManager.GetString("lblIPSubnetTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----.
        /// </summary>
        internal static string lblSeparatorTxt {
            get {
                return ResourceManager.GetString("lblSeparatorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Server.
        /// </summary>
        internal static string lblTDNSServerTxt {
            get {
                return ResourceManager.GetString("lblTDNSServerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway.
        /// </summary>
        internal static string lblTGatewayTxt {
            get {
                return ResourceManager.GetString("lblTGatewayTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string lblTIPAddressTxt {
            get {
                return ResourceManager.GetString("lblTIPAddressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Interface.
        /// </summary>
        internal static string lblTNetworkInterfaceCmbTxt {
            get {
                return ResourceManager.GetString("lblTNetworkInterfaceCmbTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Interface.
        /// </summary>
        internal static string lblTNetworkInterfaceTxt {
            get {
                return ResourceManager.GetString("lblTNetworkInterfaceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name.
        /// </summary>
        internal static string lblTProfileTxt {
            get {
                return ResourceManager.GetString("lblTProfileTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; profile applied..
        /// </summary>
        internal static string msgAppliedProfile {
            get {
                return ResourceManager.GetString("msgAppliedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings applied correctly..
        /// </summary>
        internal static string msgAppliedSetting {
            get {
                return ResourceManager.GetString("msgAppliedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you certain you want to delete the &quot;{0}&quot; profile?.
        /// </summary>
        internal static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS error,  not found network interface..
        /// </summary>
        internal static string msgErrorDNSNetworkInterface {
            get {
                return ResourceManager.GetString("msgErrorDNSNetworkInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found network interface..
        /// </summary>
        internal static string msgErrorNetworkInterface {
            get {
                return ResourceManager.GetString("msgErrorNetworkInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving profile..
        /// </summary>
        internal static string msgErrorSaving {
            get {
                return ResourceManager.GetString("msgErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply settings..
        /// </summary>
        internal static string msgErrorSetting {
            get {
                return ResourceManager.GetString("msgErrorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved profile..
        /// </summary>
        internal static string msgSaved {
            get {
                return ResourceManager.GetString("msgSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select profile to continue..
        /// </summary>
        internal static string msgSelectProfile {
            get {
                return ResourceManager.GetString("msgSelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain DNS Server Address automatically.
        /// </summary>
        internal static string rdbDNSAutomaticallyTxt {
            get {
                return ResourceManager.GetString("rdbDNSAutomaticallyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain IP Address automatically.
        /// </summary>
        internal static string rdbIpAutomaticallyTxt {
            get {
                return ResourceManager.GetString("rdbIpAutomaticallyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following DNS Server address.
        /// </summary>
        internal static string rdbSpecifyDNSTxt {
            get {
                return ResourceManager.GetString("rdbSpecifyDNSTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify an IP address.
        /// </summary>
        internal static string rdbSpecifyIpTxt {
            get {
                return ResourceManager.GetString("rdbSpecifyIpTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change IP Address.
        /// </summary>
        internal static string strMessage {
            get {
                return ResourceManager.GetString("strMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        internal static string tabConsoleTxt {
            get {
                return ResourceManager.GetString("tabConsoleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string tabNewTxt {
            get {
                return ResourceManager.GetString("tabNewTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string tabProfileTxt {
            get {
                return ResourceManager.GetString("tabProfileTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string tsbApplyTxt {
            get {
                return ResourceManager.GetString("tsbApplyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string tsbDeleteTxt {
            get {
                return ResourceManager.GetString("tsbDeleteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string tsbExitTxt {
            get {
                return ResourceManager.GetString("tsbExitTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string tsbNewTxt {
            get {
                return ResourceManager.GetString("tsbNewTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string tsbSaveTxt {
            get {
                return ResourceManager.GetString("tsbSaveTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string tsmAboutTxt {
            get {
                return ResourceManager.GetString("tsmAboutTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string tsmApplyTxt {
            get {
                return ResourceManager.GetString("tsmApplyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string tsmDeleteTxt {
            get {
                return ResourceManager.GetString("tsmDeleteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string tsmEnglishTxt {
            get {
                return ResourceManager.GetString("tsmEnglishTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string tsmExitTxt {
            get {
                return ResourceManager.GetString("tsmExitTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tsmHelpTxt {
            get {
                return ResourceManager.GetString("tsmHelpTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string tsmLanguageTxt {
            get {
                return ResourceManager.GetString("tsmLanguageTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string tsmLEnglishTxt {
            get {
                return ResourceManager.GetString("tsmLEnglishTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string tsmLSpanishTxt {
            get {
                return ResourceManager.GetString("tsmLSpanishTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string tsmNewTxt {
            get {
                return ResourceManager.GetString("tsmNewTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string tsmPreferenceTxt {
            get {
                return ResourceManager.GetString("tsmPreferenceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string tsmProfileTxt {
            get {
                return ResourceManager.GetString("tsmProfileTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string tsmSaveTxt {
            get {
                return ResourceManager.GetString("tsmSaveTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile....
        /// </summary>
        internal static string txtProfileTxt {
            get {
                return ResourceManager.GetString("txtProfileTxt", resourceCulture);
            }
        }
    }
}
